### ISSUE TITLE
任正非8月下旬发布最新讲话

### ISSUE THREAD

**Issue by pujfei** [9527001/RENZHENGFEI#1]
首先感谢小编辛勤、宝贵的工作。本库中任正非同志的历史文章，收录得很齐全，编辑质量很高，格式很精美。

其次8月下旬任正非同志又发表了数篇宏文，希望小编空闲时可以收录。

最后，华为有一个官方公众号[**蓝血研究**]，与另一个平台**华为心声社区**同步刊载任正非同志的讲话，参照这两个平台的消息，希望可以减轻小编的工作量。

**Comment by 9527001** [comment]
心声社区上8月下旬的，只发现一篇； 蓝血研究不太适合抄录。谢谢关注。
